import React from 'react';
import './Api.css';

const Api: React.FC = () => {
  return (
    <div className="api">
      <div className="api__section">
        <h1 className="api__section__header">API</h1>
        <p className="api__section__description">
          Set an <pre>Accept</pre> header to tailor the <pre>Content-Type</pre> of the response.
        </p>
        <ul>
          <li><pre>text/plain</pre></li>
          <li><pre>text/html</pre></li>
          <li><pre>text/xml</pre></li>
          <li><pre>application/json</pre></li>
        </ul>
      </div>

      <div className="api__section">
        <h2 className="api__section__header">UUID v1</h2>
        <p className="api__section__description">
          Universally Unique Identifier generated using a timestamp.
        </p>
        <p className="api__section__url"><pre>GET</pre><pre>https://uuid.app/api/v1[/$count]</pre></p>
        <table>
          <thead>
            <tr>
              <th>Variable</th>
              <th>Type</th>
              <th>Description</th>
              <th>Default</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><pre>$count</pre></td>
              <td><pre>number</pre></td>
              <td>Number of UUIDs to generate</td>
              <td><pre>1</pre></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="api__section">
        <h2 className="api__section__header">UUID v4</h2>
        <p className="api__section__description">
          Universally Unique Identifier generated randomly.
        </p>
        <p className="api__section__url"><pre>GET</pre><pre>https://uuid.app/api/v4[/$count]</pre></p>
        <table>
          <thead>
            <tr>
              <th>Variable</th>
              <th>Type</th>
              <th>Description</th>
              <th>Default</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><pre>$count</pre></td>
              <td><pre>number</pre></td>
              <td>Number of UUIDs to generate</td>
              <td><pre>1</pre></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div className="api__section">
        <h2 className="api__section__header">UUID v5</h2>
        <p className="api__section__description">
          Universally Unique Identifier generated by hasing a namespace and value.
        </p>
        <p className="api__section__url"><pre>GET</pre><pre>https://uuid.app/api/v5[/$namespace]/$value</pre></p>
        <table>
          <thead>
            <tr>
              <th>Variable</th>
              <th>Type</th>
              <th>Description</th>
              <th>Default</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><pre>$namespace</pre></td>
              <td><pre>uuid</pre></td>
              <td>Namespace used to hash</td>
              <td>URL or DNS default</td>
            </tr>
            <tr>
              <td><pre>$value</pre></td>
              <td><pre>string</pre></td>
              <td>Value to hash</td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default Api;
